apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    vault.poc.service: rabbitmq
    type: LoadBalancer
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 15672
  - name: amqp
    protocol: TCP
    port: 5672
  selector:
    vault.poc.service: rabbitmq
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      vault.poc.service: rabbitmq
  serviceName: "rabbitmq"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        vault.poc.service: rabbitmq
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        env:
        - name: "RABBITMQ_ERLANG_COOKIE"
          value: "1WqgH8N2v1qDBDZDbNy8Bg9IkPWLEpu79m6q+0t36lQ="
        volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: rabbitmq-data
      volumes:
        - name: rabbitmq-data
          hostPath:
            path: /data/rabbitmq
            type: DirectoryOrCreate