apiVersion: v1
kind: Service
metadata:
  labels:
    vault.poc.service: vault
  name: vault
spec:
  type: LoadBalancer
  ports:
  - name: "8200"
    port: 8200
    targetPort: 8200
  selector:
    vault.poc.service: vault
status:
  loadBalancer: {}